### PR TITLE
Fixes filipre/signalbot#13

### PR DESCRIPTION
**Pull request by tzabian**
Fixes filipre/signalbot#13

### CODE REVIEW

**Comment by filipre** [comment]
Hey @tzabian, 
thank you so much for your contribution! The change looks good, but the unit tests seem to fail due to the new method signature. Could you have a look there as well and include it in your PR? I can also take care of that but I am a bit busy right now and need to set up the project again.

**Comment by filipre** [comment]
Hey @tzabian,

Thank you so much for your PR! 

It looks good to me, I just fixed formatting and made the build pipeline work again. For some reason, I could not deploy your change to the test system but had to open the PR myself. In any case, could you have a look at https://github.com/filipre/signalbot/pull/16#issuecomment-1383126774 or https://test.pypi.org/project/signalbot/0.6.0a1673782638/ and test it in your project? If everything works for you, I can deploy it to production.

Best
René

**Comment by Kariton** [comment]
Hey,
I use this test version and it works great!
Need it for `raw_message`, though.

Really love what you (and others!) have done here!

(ctx: Context)
_I feel like_ `ctx.message.raw_message` does not belong to `ctx.message` in its current form.
I understand `ctx.message` more like a "friendly" way to access different aspects of `raw_message`.
But I dont know if somethink like `ctx.raw_message` is feasible.

maybe I misinterpreted the "scope".

**Comment by Kariton** [comment]
Well... while writing #17 i discovered that `raw_message` is empty if you reply.

```
ctx.message (Context):  {'source': 'REDACTED', 'timestamp': 1675193291251, 'type': <MessageType.DATA_MESSAGE: 2>, 'text': 'reply test', 'group': 'REDACTED', 'reaction': None, 'raw_message': None}
ctx.message.raw_message: null
ctx.message.text: reply test
```

**Pull request merged**
